charter.md

- do not commit to a specific time frame
- insist on the stability questions
- mention the Linux distribution stakeholders
- remove any objective regarding Coq's CI
- summarize the categories of stakeholders
- add some unresolved questions

Refine charter / add unresolved questions.

---

charter.md

Prompted by @palmskog in Zulip.

Some notes and unresolved questions on dependencies.

---

.github/workflows/ci.yml
README.md
coq_platform_packages.sh

This PR adds 2 CI improvements:
- run a Windows 32 bit test (using the matrix feature) - this should go into master and release branches
- do a daily run - only to be merged in master

CI improvements

---

.github/workflows/ci.yml
shell_scripts/create_smoke_test_kit.sh

(includes useful commit from v8.13)

Smoke artifact & CI job

---

coq_platform_packages.sh
opam/packages/coq-vst-32/coq-vst-32.2.7/files/makefile.patch
opam/packages/coq-vst-32/coq-vst-32.2.7/opam
opam/packages/coq-vst/coq-vst.2.7/files/makefile.patch
opam/packages/coq-vst/coq-vst.2.7/opam
opam/packages/coq/coq.8.13.0/files/coq.install
opam/packages/coq/coq.8.13.0/opam
opam/packages/coqide/coqide.8.12.0/files/coqide.install
opam/packages/coqide/coqide.8.13.0/files/coqide.install
opam/packages/coqide/coqide.8.13.0/opam

Coq V8.13.0

---

linux/snap/snapcraft.yaml.in

[snap] add make

---

coq_platform_make.sh
opam/packages/gappa/gappa.1.3.5/files/0001-Added-configure-for-c-11.patch
opam/packages/gappa/gappa.1.3.5/files/remake.patch
opam/packages/gappa/gappa.1.3.5/opam
shell_scripts/init_cygwin_fixes.sh
shell_scripts/install_opam.sh

This PR fixes the source chekcsum of gappa - for some reason this is failing on Windows but not on other systems.

Gappa: fix source checksum

---

.github/workflows/macos.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
.gitignore
linux/create_linux_installer.sh
macos/create_installer_macos.sh
shell_scripts/create_smoke_test_kit.sh

[ci] Add dmg package

---

.gitignore
coq_platform_packages.sh
shell_scripts/create_smoke_test_kit.sh

Add HoTT 8.13

---

linux/create_linux_installer.sh
linux/snap/coq-prover.desktop.in
linux/snap/coq_wrapper
linux/snap/coq_wrapper_coq_makefile
linux/snap/coq_wrapper_coqc
linux/snap/coq_wrapper_coqide
linux/snap/coq_wrapper_coqidetop.opt
linux/snap/coq_wrapper_coqtop
linux/snap/snapcraft.yaml.in

snap: fix Exec field of .desktop + clightgen

---

shell_scripts/install_opam.sh

Fixes typo in `shell_scripts/install_opam.sh`

---

coq_platform_make.sh
notes/opam-depext.md
shell_scripts/install_opam_depext.sh
shell_scripts/install_pkg-config.sh
shell_scripts/install_prerequisites_coqide.sh
shell_scripts/install_prerequisites_gappa.sh

Adjust scripts to latest opam 2.1.0, which integrates depext

---

.github/workflows/macos.yml
.github/workflows/snap.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
coq_platform_make_windows.bat
coq_platform_packages.sh
example_coq_platform_make.sh
example_coq_platform_make_windows.bat
linux/snap/github_actions/README.md
linux/snap/github_actions/run_snap.sh
shell_scripts/ask_compcert_open_source.sh
shell_scripts/ask_vst.sh
shell_scripts/parse_cmdline_arguments.sh

since CompCert does not support it

Remove open source option for CompCert

---

.github/workflows/snap.yml

This fixes the snap issues with refreshing LXD

CI: set snapcore/action-build version to v1.0.9

---

maintainer_scripts/notify-upstream-pins.sh
opam/opam-coq-archive/extra-dev/packages/coq-vst-32/coq-vst-32.dev/files/0001-Fix-issue-485-make-install-with-IGNORECOQVERSION.patch
opam/opam-coq-archive/extra-dev/packages/coq-vst-32/coq-vst-32.dev/opam
opam/opam-coq-archive/extra-dev/packages/coq-vst/coq-vst.2.8~flex/files/0001-Fix-issue-485-make-install-with-IGNORECOQVERSION.patch
opam/opam-coq-archive/extra-dev/packages/coq-vst/coq-vst.2.8~flex/opam
opam/opam-coq-archive/extra-dev/packages/coq-vst/coq-vst.dev/files/0001-Fix-issue-485-make-install-with-IGNORECOQVERSION.patch
opam/opam-coq-archive/extra-dev/packages/coq-vst/coq-vst.dev/opam

(this also fixes the 8.14 smoke test)

Fix VST ~flex preview opam packages

---

README.md
shell_scripts/closing_remarks.sh

Also correct the information in "closing_remarks.sh"

README: add section which explains how to use several Coq versions in parallel

---

notes/opam-depext.md
shell_scripts/ask_packagelist.sh
shell_scripts/ask_parallel_build.sh
shell_scripts/closing_remarks.sh
shell_scripts/get_names_from_switch.sh
shell_scripts/init_cygwin_fixes.sh
shell_scripts/init_utilities.sh
shell_scripts/install_opam.sh
shell_scripts/sanitize_environment.sh
windows/configure_profile.sh

Courtesy of https://github.com/crate-ci/typos

Spelling fixes

---

linux/snap/snapcraft.yaml.in

- change file filter for bin folder from positive to negative list
- further restruct file filer for lib folder (exclude coq-xyz)

Snap: Fix #243

---

.github/workflows/macos.yml
macos/create_installer_macos.sh

Co-authored-by: Enrico Tassi <Enrico.Tassi@inria.fr>

MacOS: fix issue with macpack during DMG installer creation

---

macos/Installation.html.template
macos/create_installer_macos.sh

Add note in macOS Install.html on notarisation issue - fixes #325

Fix issue with installer for macOS ARM / Apple silicon

---

.github/workflows/ubuntu.yml
linux/example_build_snap_lxd.sh
linux/snap/coq_wrapper
linux/snap/snapcraft.yaml.in
shell_scripts/init_machine_type.sh

Fix snap by using --destructive mode with core 20 on Ubuntu20.04 runner to build snap

Snap: enabled snap + smoke test

---

linux/snap/coq_wrapper

coq_wrapper: pass COQBIN as the last argument

---

maintainer_doc/release_process.md
maintainer_scripts/package-version-info.sh
maintainer_scripts/packages_already_processed.txt
opam/opam-coq-archive/released/packages/coq-compcert/coq-compcert.3.13.1/opam
opam/opam-coq-archive/released/packages/coq-fiat-crypto/coq-fiat-crypto.0.0.22/opam
opam/opam-coq-archive/released/packages/coq-simple-io/coq-simple-io.1.8.0/opam
opam/opam-coq-archive/released/packages/coq-unicoq/coq-unicoq.1.6+8.18/opam
opam/opam-coq-archive/released/packages/coq-unimath/coq-unimath.20230420/opam
package_picks/package-pick-8.18+beta1.sh

This PR adds the initial pick for 2023.09/10 reflecting the state on which the "please pick" issues are based.

Prepare 2023.09 1

---

opam/opam-coq-archive/released/packages/coq-corn/coq-corn.8.18.0/opam
package_picks/package-pick-8.18+beta1.sh

Adding the latest coq-corn tag (as required from [here](https://github.com/coq-community/corn/issues/200))

New tag for coq-corn

---

.github/workflows/macos.yml
maintainer_doc/release_process.md

- removed minimum OS version selection from macos.yaml - this is automatic now

Added more details on release process to maintainer_doc/release_process.md

---

doc/README_macOS.md

Removing parts of the readme referring to apple silicon

---

windows/create_installer_windows.sh

Attempting to fix Coq CI (c.f., https://github.com/coq/platform/pull/456#issuecomment-2592861828 )

Renaming coqide -> rocqide
