.github/workflows/ci.yml

I've extracted from #44 the commit adding CI to the platform, based on work by @Zimmi48. Two things before merge:
This commit should work just fine on the v8.12 branch

[ci] GH actions for windows, linux and osx

---

README.md
coq_platform_packages.sh
opam/packages/coq-compcert-32/coq-compcert-32.dev/opam
opam/packages/coq-compcert/coq-compcert.dev/opam
opam/packages/coq-flocq/coq-flocq.3.dev/opam

Add back CompCert after switching to Flocq-3.
Note: The man page issue seen in opam-coq-archive CI d

CompCert: add back after adjusting Flocq to flocq-3 branch

---

.github/workflows/snap.yml
linux/create_linux_installer.sh
linux/snap/README.md
linux/snap/coq_wrapper
linux/snap/coq_wrapper_coq_makefile
linux/snap/coq_wrapper_coqc
linux/snap/coq_wrapper_coqide
linux/snap/coq_wrapper_coqidetop.opt
linux/snap/coq_wrapper_coqtop
linux/snap/coqide.desktop.in
linux/snap/github_actions/README.md
linux/snap/github_actions/run_snap.sh
linux/snap/snapcraft.yaml.in

Request for aliases (coqide and coq_makefile) is ongoing here: https://forum.snapcraft.io/t/aliases-request-for-coq-prover/21925
@MSoegtropIMC this is now ready for review. There are a few things to document:
- the package is not just bundling files already present, it runs the platform script from the snap building infrastructure (unlike we do on windows, hence the job is not on top of the ubuntu one), hence...
- the job builds a minimal platform unless told otherwise, and does not upload the snap in the store. One has to trigger a manual build. On the default branch of the repo this can be done using a web UI, but for other branches one has to do a call to the API of github. The script `github_actions/run_snap.sh` can do it. The idea is that the job is run "in full" only when one wants …

[CI] Add snap package

---

shell_scripts/init_cygwin_fixes.sh

Revert MinGW 64 bit binutils to version 2.35.1-1.
There is some evidence that the latest version causes CI failures.

Cygwin64: revert MinGW 64 binutils to 2.35.1-1

---

coq_platform_make.sh
shell_scripts/init_cygwin_fixes.sh

This is the same as #73 for master (also including the previous cygwin32 fix)

Cygwin64: revert MinGW 64 binutils to 2.35.1-1 (master branch)

---

coq_platform_packages.sh
opam/packages/conf-pkg-config/conf-pkg-config.2/opam

Fix the cygwin depext package name for conf-pkg-config

opam conf-pkg-config: fix package name for cygwin

---

charter.md

In particular, this removes a bunch of now resolved questions.

Charter clean-up after CEP 52.

---

windows/Coq.nsi

Also remove coqtop from the start menu, I think it'll just confuse users, especially as it's installed as "Coq"
See https://coq.zulipchat.com/#narrow/stream/250632-Coq-Platform.20devs.20.26.20users/topic/Windows.20icons/near/238308109
Is this the right branch to propose for?

Rename CoqIde to CoqIDE and add icon

---

coq_platform_make_windows.bat

This PR improves the consistency of the used cygwin cache folder path in case `coq_platform_make_windows.bat` is called from cygwin (not that uncommon to clone the repo in another cygwin).

Windows: improved consistency of cygwin cache path

---

windows/create_installer_windows.sh

This PR adjusts the NSIS download URL to changes in the SourceForge infrastructure.

Windows: adjust download URL for NSIS installer

---

windows/create_installer_windows.sh

Since the new SF download URL for NSIS didn't prove terribly stable either, we created a new github project coq/prerequisites to host the prerequisite tar balls in a stable way.
This PR moves the NSIS download URL to this new repo.

Windows: move nsis download URL to coq/prerequisites

---

windows/Coq.nsi

It is best practice to include the publisher name in the Add/Remove Programs table on Windows. This change sets the publisher name for the package

Add Publisher to Registry Entries

---

shell_scripts/ask_introduction.sh

If there is a better way to do this, please feel free to edit. I was wrongly under the impression that full > extended having not read the description very carefully and as the order of these options' descriptions did not match the options presented.

Map the package options with descriptions

---

linux/snap/snapcraft.yaml.in

Coq 8.15 installs stuff in lib/coq and lib/coq-core (and maybe also lib/coq-stlib).

[snap] do not purge lib/coq-core

---

shell_scripts/init_cygwin_fixes.sh

(required since python2 was removed from cygwin)

Windows: use python3 as default python

---

package_picks/package-pick-8.18+beta1.sh

This might be final, except that we want to split this into two separate picks, one based on mathcomp 1.18 and one based on 2.1 since mathcomp-analysis and mathcomp-word are not available for mc 2.x as yet.

Prepare 2023.10 2

---

opam/opam-coq-archive/released/packages/coq-metacoq-template/coq-metacoq-template.1.2+8.16/opam
opam/opam-coq-archive/released/packages/coq-metacoq-template/coq-metacoq-template.1.2+8.17/opam
opam/opam-coq-archive/released/packages/coq-metacoq-template/coq-metacoq-template.1.2.1+8.18/opam
opam/opam-coq-archive/released/packages/coq-metacoq-template/coq-metacoq-template.1.3.1+8.19/opam

As discussed in [Zulip](https://coq.zulipchat.com/#narrow/stream/237658-MetaCoq/topic/coq-metacoq-template.201.2E2.2E1.2B8.2E18.20suddenly.20failing.20in.20CI/near/453432560) both the patch and the rm are needed for stable builds.

Opam: coq-metacoq-template: add back the 'rm _PluginProject' fix

---

package_picks/package-pick-8.19~2024.01+beta1.sh
shell_scripts/ask_long_path.sh
shell_scripts/init_cygwin_fixes.sh
windows/default-manifest.rc
windows/long-paths.md

should permanently fix coq-serapi issues

Windows: enable long path support in cygwin MinGW toolchain and Windows registry

---

coq_platform_make.sh
opam/opam-coq-archive/released/packages/coq-mtac2/coq-mtac2.1.4+8.19/files/0001-use-new-way-of-loading-ML-module-makes-Unicoq-module.patch
opam/opam-coq-archive/released/packages/coq-mtac2/coq-mtac2.1.4+8.19/opam
opam/opam-coq-archive/released/packages/coq-quickchick/coq-quickchick.2.0.3/files/0001-Fix-mycppo-script-for-Windows.patch
opam/opam-coq-archive/released/packages/coq-quickchick/coq-quickchick.2.0.3/opam
package_picks/package-pick-8.19~2024.01+beta1.sh
shell_scripts/install_ocaml_stacksize.sh
windows/set_stack_size/dune
windows/set_stack_size/dune-project
windows/set_stack_size/set_stack_size.ml

Note: the fix for coq-quickchick is only partial, but an improvement.

Windows package fixes

---

opam/opam-repository/packages/z3_tptp/z3_tptp.4.13.3/opam
package_picks/package-pick-8.20~2025.01.sh

Update a few package versions according to "please pick issues".

2025.01 prep 4

---

package_picks/package-pick-8.14~2022.01.sh
package_picks/package-pick-8.14~2022.04.sh
package_picks/package-pick-8.15~2022.04.sh
package_picks/package-pick-8.15~2022.09.sh
package_picks/package-pick-8.16~2022.09.sh
package_picks/package-pick-8.16~2023.08.sh
package_picks/package-pick-8.17~2023.08.sh
package_picks/package-pick-8.18~2023.11.sh
package_picks/package-pick-8.18~mc2.sh
package_picks/package-pick-8.20~2025.01.sh

Pick 8.20~2025.01:
- updated coq-coqprime to version 1.6.0
- updated coq-libhyps to version 3.0.1
- enabled coq-reglang.1.2.1 (depended on mathcomp-analysis fix)
- enabled coq-extructures (depended on mathcomp-analysis fix)
- updated coq-mathcomp-real-closed to version 2.0.2 and enabled it
- updated coq-coqeal to version 2.0.3 and enabled it
- updated coq-mathcomp-analysis to version 1.8.0 (the above two updates depend on this)

2025.01 prep 6
